import { describe, it, expect } from "vitest";
import {
  BCF_MAP_VIEWBOX,
  bcfProjectPin,
} from "@/components/Sections/bcf/bcfMapGeometry";
import {
  BCF_KRI_DISTRICTS,
  BCF_KRI_ROADS,
  BCF_KRI_TOWNS,
} from "@/components/Sections/bcf/bcfKurdistanDetail";

/**
 * The zoomable Region map is one drawing, not a stack of them.
 *
 * Districts, roads, rivers and towns are generated by
 * scripts/build-bcf-kurdistan-detail.mjs with the four projection constants
 * recovered in bcfMapGeometry.ts, and the thirteen pins are placed by
 * `bcfProjectPin` with those same four. That agreement is the whole reason the
 * zoom can be a camera over a single plate instead of two maps kept in register
 * by hand — and it is invisible until someone re-runs the generator against a
 * differently projected source, at which point Erbil sits in a field outside
 * Erbil and nothing else complains.
 *
 * So it is asserted: a city projected by the app must land inside the district
 * ring generated for it.
 */

/** `M x,y x,y … Z` — the implicit-lineto form every generated path uses. */
function rings(d: string): [number, number][][] {
  return d
    .split("M")
    .filter(Boolean)
    .map((part) =>
      part
        .replace(/Z/g, "")
        .trim()
        .split(/\s+/)
        .map((pair) => pair.split(",").map(Number) as [number, number]),
    );
}

function inRing(x: number, y: number, ring: [number, number][]) {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    if (yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) {
      inside = !inside;
    }
  }
  return inside;
}

/** A pin's percentage of the plate, back in the plate's own user units. */
function pinUnits(lon: number, lat: number) {
  const pin = bcfProjectPin(lon, lat);
  return {
    x: BCF_MAP_VIEWBOX.minX + (parseFloat(pin.x) / 100) * BCF_MAP_VIEWBOX.width,
    y: BCF_MAP_VIEWBOX.minY + (parseFloat(pin.y) / 100) * BCF_MAP_VIEWBOX.height,
  };
}

describe("Kurdistan detail geometry", () => {
  it.each([
    ["erbil", 44.009, 36.191],
    ["duhok", 42.988, 36.868],
    ["zakho", 42.681, 37.144],
    ["al-sulaymaniyah", 45.436, 35.561],
    ["halabcha", 45.986, 35.178],
  ])("puts %s inside its own district ring", (id, lon, lat) => {
    const district = BCF_KRI_DISTRICTS.find((shape) => shape.id === id);
    expect(district, `no district "${id}" — did the generator's source change?`)
      .toBeDefined();
    const { x, y } = pinUnits(lon, lat);
    expect(rings(district!.d).some((ring) => inRing(x, y, ring))).toBe(true);
  });

  it("draws nothing outside the plate the pins are placed on", () => {
    const bounds = {
      minX: BCF_MAP_VIEWBOX.minX - 30,
      maxX: BCF_MAP_VIEWBOX.minX + BCF_MAP_VIEWBOX.width + 30,
      minY: BCF_MAP_VIEWBOX.minY - 30,
      maxY: BCF_MAP_VIEWBOX.minY + BCF_MAP_VIEWBOX.height + 30,
    };
    for (const town of BCF_KRI_TOWNS) {
      expect(town.x).toBeGreaterThanOrEqual(bounds.minX);
      expect(town.x).toBeLessThanOrEqual(bounds.maxX);
      expect(town.y).toBeGreaterThanOrEqual(bounds.minY);
      expect(town.y).toBeLessThanOrEqual(bounds.maxY);
    }
    /* One merged path per road class, so a stray segment on the far side of the
       window would otherwise be invisible until someone zoomed onto it. */
    for (const [name, d] of Object.entries(BCF_KRI_ROADS)) {
      for (const ring of rings(d)) {
        for (const [x, y] of ring) {
          expect(
            x >= bounds.minX && x <= bounds.maxX && y >= bounds.minY && y <= bounds.maxY,
            `${name} leaves the plate at ${x},${y}`,
          ).toBe(true);
        }
      }
    }
  });

  it("names every town in all three languages", () => {
    expect(BCF_KRI_TOWNS.length).toBeGreaterThan(50);
    for (const town of BCF_KRI_TOWNS) {
      expect(town.en.length).toBeGreaterThan(0);
      expect(town.ku.length).toBeGreaterThan(0);
      expect(town.ar.length).toBeGreaterThan(0);
    }
  });
});
