export const threadsCopy = {
    en: {
      languageName: "English",
      attractEyebrow: "The living memory of a shared homeland",
      attractTitle: "Kurdistan",
      attractCaption: ["The cradle of coexistence"],
      enter: "Touch to enter",
      enterHint: "Follow the living threads",
      chooseLanguage: "Choose your language",
      chooseLanguageHint: "Your choice stays with you throughout the journey.",
      hubEyebrow: "Five living threads · one shared story",
      hubTitle: "A land where many peoples share one home",
      hubBody:
        "This journey invites you into Kurdistan's story of coexistence — through faiths, nations, courageous leadership, shared life, and the rights that protect belonging.",
      hubQuote: "Not enduring the other — celebrating one another.",
      hubInstruction: "Touch a thread",
      hubInstructionHint: "to follow its story",
      threadLabel: "Living thread",
      storyInstruction: "Touch a subject to explore its four photo stories",
      openStory: "Read more",
      collectionLabel: "Photo collection",
      previous: "Previous",
      next: "Next",
      back: "Back",
      home: "Threads",
      language: "Language",
      closing: "The woven future",
      closingEyebrow: "The threads return to one centre",
      closingTitle: "We are one living homeland.",
      closingLines: [
        "Every identity has value.",
        "Every community belongs.",
        "The future is built together.",
      ],
      closingCore: "KURDISTAN",
      closingCoreHint: "One shared homeland",
      returnToThreads: "Explore another thread",
      visited: "threads discovered",
      idleTitle: "Still exploring?",
      idleBody: "The experience will return to its opening scene.",
      idleContinue: "Continue",
    },
    ku: {
      languageName: "کوردی",
      attractEyebrow: "یادەوەری زیندووی وڵاتێکی هاوبەش",
      attractTitle: "کوردستان",
      attractCaption: ["لانکەی پێکەوەژیان"],
      enter: "دەست لێبدە بۆ چوونە ژوورەوە",
      enterHint: "بەدوای تەنە زیندووەکاندا بڕۆ",
      chooseLanguage: "زمانەکەت هەڵبژێرە",
      chooseLanguageHint: "هەڵبژاردنەکەت لە تەواوی گەشتەکەدا دەمێنێتەوە.",
      hubEyebrow: "پێنج تەنە زیندوو · یەک چیرۆکی هاوبەش",
      hubTitle: "وڵاتێک کە گەلانی زۆر یەک ماڵی هاوبەشە",
      hubBody:
        "ئەم گەشتە بانگهێشتی چیرۆکی پێکەوەژیانی کوردستان دەکات — لە ڕێگەی ئایین، نەتەوە، ڕێبەرایەتیی ئازا، ژیانی هاوبەش و ئەو مافانەی سەربەخۆیی دەپارێزن.",
      hubQuote:
        "پێکەوەژیان تەنها دانبەخۆداگرتن نییە بەرامبەر ئەوی تر، بەڵکو بەرزڕاگرتنیەتی.",
      hubInstruction: "دەست لە تەنێک بدە",
      hubInstructionHint: "بەدوای چیرۆکەکەیدا بڕۆ",
      threadLabel: "تەنە زیندووەکە",
      storyInstruction: "دەست لە بابەتێک بدە بۆ دۆزینەوەی چوار چیرۆکی وێنەدار",
      openStory: "زیاتر بخوێنەوە",
      collectionLabel: "کۆمەڵە وێنە",
      previous: "پێشوو",
      next: "دواتر",
      back: "گەڕانەوە",
      home: "تەنەکان",
      language: "زمان",
      closing: "داهاتووی چنراو",
      closingEyebrow: "تەنەکان دەگەڕێنەوە بۆ یەک ناوەند",
      closingTitle: "ئێمە یەک وڵاتی زیندووین.",
      closingLines: [
        "هەر ناسنامەیەک بەهای خۆی هەیە.",
        "لێرە شوێن بۆ هەمووان هەیە.",
        "داهاتوو پێکەوە بنیاد دەنرێت.",
      ],
      closingCore: "کوردستان",
      closingCoreHint: "یەک نیشتمانی هاوبەش",
      returnToThreads: "تەنێکی تر بدۆزەوە",
      visited: "تەن دۆزراوەتەوە",
      idleTitle: "هێشتا دەگەڕێیت؟",
      idleBody: "ئەزموونەکە دەگەڕێتەوە بۆ دیمەنی سەرەتا.",
      idleContinue: "بەردەوام بە",
    },
    ar: {
      languageName: "العربية",
      attractEyebrow: "الذاكرة الحية لوطن مشترك",
      attractTitle: "كوردستان",
      attractCaption: ["مهد التعايش"],
      enter: "المس للدخول",
      enterHint: "اتبع الخيوط الحية",
      chooseLanguage: "اختر لغتك",
      chooseLanguageHint: "سيبقى اختيارك معك طوال الرحلة.",
      hubEyebrow: "خمسة خيوط حية · قصة واحدة مشتركة",
      hubTitle: "أرض يشترك فيها كثير من الشعوب في وطن واحد",
      hubBody:
        "هذه الرحلة تدعوك إلى قصة التعايش في كوردستان — عبر الأديان والقوميات والقيادة الشجاعة والحياة المشتركة والحقوق التي تحفظ الانتماء.",
      hubQuote: "التعايش ليس تحمّل الآخر. بل هو الاحتفاء به.",
      hubInstruction: "المس خيطاً",
      hubInstructionHint: "لتتبع حكايته",
      threadLabel: "الخيط الحي",
      storyInstruction: "المس موضوعاً لاستكشاف أربع حكايات مصوّرة",
      openStory: "اقرأ المزيد",
      collectionLabel: "مجموعة مصوّرة",
      previous: "السابق",
      next: "التالي",
      back: "العودة",
      home: "الخيوط",
      language: "اللغة",
      closing: "المستقبل المنسوج",
      closingEyebrow: "الخيوط تعود إلى مركز واحد",
      closingTitle: "نحن وطن حي واحد.",
      closingLines: [
        "كل هوية لها قيمة.",
        "كل مجتمع ينتمي.",
        "المستقبل يُبنى معاً.",
      ],
      closingCore: "كوردستان",
      closingCoreHint: "وطن مشترك واحد",
      returnToThreads: "استكشف خيطاً آخر",
      visited: "خيوط مكتشفة",
      idleTitle: "هل ما زلت تستكشف؟",
      idleBody: "ستعود التجربة إلى مشهد البداية.",
      idleContinue: "متابعة",
    },
  } as const;
export type ThreadsLang = keyof typeof threadsCopy;
export type ThreadsCopy = (typeof threadsCopy)[ThreadsLang];
